# Generated by Django 4.1.2 on 2022-11-18 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid Email')]),
        ),
    ]
